on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6
        with:
          run_install: true

      - name: Lint project
        run: pnpm run lint:ci --css-parse-tailwind-directives=true

      - name: Prettier check
        run: pnpm run format:check

      - name: Astro Check
        run: pnpm run check

      - name: Build project
        run: pnpm run build
